
<div class="row">

    <div class="col-md-12">
        <h2>Error :/</h2>
        <?=kiss\base\Template::render("/error/partials/_error.phtml", array('errors'=>$mvc->scope['errors'])); ?>
    </div>
    
    
     <? if( $mvc->scope['exception'] ):?>
     <div class="col-md-12">
           <table class="table table-striped">
            <tbody>
            <? foreach($mvc->scope['exception'] as $k=>$e):?>
                <tr>
                    <td><?=$k?></td>
                    <td><?=htmlentities($e)?></td>
                </tr>
            <?endforeach;?>
            
            </tbody>
            </table>
     </div>
     <?endif;?>
    
</div>
