<? $mvc->setScript('/js/views/auth/join.js'); ?>

<h2> Join Us...</h2>

<? if( $mvc->authError ): ?>

    <div class="alert alert-warning">User exists:</div>
    
    <div class="btn-group">
        <a href="/auth/login" class="btn btn-default">Login</a> 
        <a href="/auth/join"  class="btn btn-default">Join again</a>
        <a href="/auth/pass"  class="btn btn-default">I forgot my password</a>
    </div>

<? else: ?>


<div class="row">

    <div class="col-md-4">
        <?=$mvc->form?>
    </div>    

    <div class="col-md-6">
        
        <strong>Passwords Requirements:</strong>
        
        <ul id="password-requirements" class="well lists-no-style">
            <li id="pass-gtheq-8">The password length must be greater than or equal to 8</li>
            <li id="pass-one-upper">The password must contain one or more uppercase characters</li>
            <li id="pass-one-lower">The password must contain one or more lowercase characters</li>
            <li id="pass-one-number">The password must contain one or more numeric values</li>
            <li id="pass-one-special">The password must contain one or more special characters</li>
        </ul>     
    </div>    

</div>



<? endif; ?>