<h2>Join</h2>

<? if( $mvc->authError ): ?>

    <div class="alert alert-warning">User exists:</div>
    
    <div class="btn-group">
        <a href="/auth/login" class="btn btn-default">Login</a> 
        <a href="/auth/join"  class="btn btn-default">Join again</a>
        <a href="/auth/pass"  class="btn btn-default">I forgot my password</a>
    </div>

<? else: ?>

    <?=$mvc->form?>

<? endif; ?>