<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?= isset($mvc->scope['title']) ? $mvc->scope['title'] : "Welcome - ". SITE_NAME; ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
        <?= $mvc->getStyles(); ?>
        
        <!--[if lt IE 9]>
            <script src="/js/vendor/html5-3.6-respond-1.1.0.min.js"></script>
        <![endif]-->
        
    </head>
    <body>
        
        <div class="container">
            <?= $mvc->content ?>
        </div>
        
        <script src="/js/vendor/jquery-1.11.0.min.js"></script>
        <script src="/js/vendor/bootstrap.min.js"></script>
        <?= $mvc->getScripts(); ?>
    </body>
</html>        
