<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?= isset($mvc->scope['title']) ? $mvc->scope['title'] : "Welcome - ". SITE_NAME; ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/css/main.css">
        <?= $mvc->getStyles(); ?>
       
        <script src="/js/vendor/jquery-1.11.0.min.js"></script>
        <script src="/js/vendor/bootstrap.min.js"></script>
        <!--[if lt IE 9]>
            <script src="/js/vendor/html5-3.6-respond-1.1.0.min.js"></script>
        <![endif]-->
        
    
    </head>
    <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Kiss</a>
        </div>
        <div class="navbar-collapse collapse">
        
          <? if(!$mvc->isLogged()):?>  
            
          <form id="login" role="form" class="depage-form navbar-form navbar-right"
                enctype="multipart/form-data" data-jsautosave="false" data-jsvalidation="blur" action="/auth/login" method="POST" name="login">  
            <input name="formName" id="login-formName" class="input-hidden" value="login" type="hidden">
            <div class="form-group">
              <input type="text" placeholder="Username" name="username" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" name="password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
          
          <?else:?>
          <form id="login" role="form" class="depage-form navbar-form navbar-right">
         
          <div class="form-group">
            <a href="/account" class="btn btn-default"> My Account </a>
          </div>
          
          <a href="/auth/logout" class="btn btn-warning">Logout</a>
          </form>
          <?endif;?>
        
        </div>
        
        <!--/.navbar-collapse -->
      </div>
    </div>

    <div class="container wrapper">
        <?= $mvc->content ?>
        <div class="push"> </div>
    </div>

    <div class="footer navbar-inverse">
        <div class="container">
            <div class="row">
                <p class="powered-by">Powered by <a href="<?=kiss\base\Settings::read('SITE_URL')?>"
                target="_blank"><?=kiss\base\Settings::read('SITE_NAME')?></a> &copy; <?=date("Y")?></p>
            </div>
        </div>
    </div>

        <script src="/js/main.js"></script>
        <?= $mvc->getScripts(); ?>
    </body>
</html>        

        

